Implement Bootstrap service
cibr-qcri/defi-robo-advisor pull request #7
Opened 2022-05-27 17:13 UTC by thedarkspy

Closes #1

2022-05-28 07:12 UTC, boshmaf requested changes

2022-05-28 07:12 UTC, boshmaf commented on services/README.md
> +This repo contains a set of services that are used for collecting data about DeFi protocols
directory, not repo, contains a set of...

2022-05-28 07:12 UTC, boshmaf commented on services/README.md
> +```
The services are all run together from the parent directory using docker-compose.

I'd add a section on how to debug the service using docker-compose logs, and when to down/up to get it started. I'd also write about that some services should stay running in an event-loop (simplest form is a timeout in an infinite loop, but you have to be careful). Also, I'd mention that some services depend on other services, and the way they can check is if the service on which they depend on has written some new data to its collection.

If they need to run the service on its own, they need a mongo container running with all required collections --- can get complicated --- so it's better to do this from the parent docker-compose that has all dependencies.

2022-05-28 07:12 UTC, boshmaf commented on services/bootstrap/run.js
> +    }
I'd move this to a separate function to make it more modular. Other services might have more complicated logic (e.g., if data exists but older than a week, get it again), and having everything in the mean function will make the code difficult to maintain.  

You basically have three actions:
- shouldGetData
- getData
- storeData

2022-05-28 07:12 UTC, boshmaf commented on services/bootstrap/run.js
> +    const jsonData = response.data;
Same here.

2022-05-28 07:12 UTC, boshmaf commented on services/bootstrap/run.js
> +      await Protocol.create(protocol);
And here.

2022-05-28 14:10 UTC, thedarkspy commented on services/bootstrap/run.js
> +    }
Modified the service based on your feedback. For this case, I did not implement shouldGetData because now when storing data, it basically checks when adding new protocols if they already exist.

2022-05-28 14:23 UTC, thedarkspy commented on services/README.md
> +```
README file updated. Please check and let me know.

2022-05-28 14:58 UTC, boshmaf requested changes

2022-05-28 14:58 UTC, boshmaf commented on services/bootstrap/run.js
> +  const API_URL = 'https://api.llama.fi/protocols';
Should go to docker-compose as env variable (see other repos for an example)

2022-05-28 14:58 UTC, boshmaf commented on services/bootstrap/run.js
> +    console.log('Halting due to an error...');
Still print the error so it's more likely to know what happened

2022-05-28 14:58 UTC, boshmaf commented on services/bootstrap/run.js
> +      await sleep(nextRunTime.getTime() - currentTime);
I'd move this to a new function like wait(), and for this service it's waiting until the a time times out. In other places, it could be a network call, etc. Also, the sleep util function should take durationMs as an input, and that value should be coming from an env var set in docker-compose (i.e., process.env.sleepDurationMs).
```javascript
while (true) {
  const data = await getData(process.env.API_URL)
  await storeData(data)
  await wait(process.env.sleepDurationMs) // should be implemented here
}
```

2022-05-28 14:58 UTC, boshmaf commented on services/bootstrap/run.js
> +};
Should go to utils as it's generic, also you can add params for query params and pass it if set.
```javascript
console.log('Fetching protocol data from API...');
const response = await axios.get(URL, params);

return response.data;
```

2022-05-28 14:58 UTC, boshmaf commented on services/bootstrap/run.js
> +    }
Two approaches here: Keep the last version (the one you just pulled), or add new values. For the latter, you need a new collection, say Market, which references protocol by id and has the dynamic market props like tvl, chainTvls, marketCap, fullyDilutedVolume). This needs to be timestamps. This way you can plot tvl over time per protocol too.

I think we should go with the latter approach.

2022-05-28 14:58 UTC, boshmaf commented on services/common/utils.js
> +module.exports.sleep = (timeMs) => {
Should accept duration in Ms and calculates timeMs.

2022-05-28 15:03 UTC, thedarkspy commented on services/common/utils.js
> +module.exports.sleep = (timeMs) => {
It is actually duration, but bad naming. Will rename.

2022-05-28 15:04 UTC, thedarkspy commented on services/bootstrap/run.js
> +};
I think this way we are over-simplifying it. It is already simple to use from axios. They might need to use get, post and/or other methods that do not need to be re-defined in our code.

2022-05-28 15:06 UTC, thedarkspy commented on services/bootstrap/run.js
> +      await sleep(nextRunTime.getTime() - currentTime);
This way all services will sleep for the same duration, otherwise we will need an env variable for each service. I think each service should sleep for how much is necessary for its goal/requirements.

2022-05-28 15:06 UTC, thedarkspy commented on services/bootstrap/run.js
> +    console.log('Halting due to an error...');
It is still printed in the first console.log

2022-05-28 15:14 UTC, thedarkspy commented on services/bootstrap/run.js
> +  const API_URL = 'https://api.llama.fi/protocols';
Done

2022-05-28 15:14 UTC, thedarkspy commented on services/bootstrap/run.js
> +      await sleep(nextRunTime.getTime() - currentTime);
Done

2022-05-28 15:23 UTC, thedarkspy commented on services/bootstrap/run.js
> +    }
I am not sure if I get the idea behind this

2022-05-29 06:09 UTC, boshmaf commented on services/bootstrap/run.js
> +    console.log('Halting due to an error...');
`console.log('Service exiting due to an unhandled error', error);` And you can remove the first log statement.

2022-05-29 06:10 UTC, boshmaf commented
@thedarkspy please request the review again

2022-05-29 06:11 UTC, boshmaf commented on services/bootstrap/run.js
> +};
Leaving it in the script is fine, as long as it's its own function.

2022-05-29 06:12 UTC, boshmaf commented on services/bootstrap/run.js
> +    }
Let's pair program to save time.

2022-05-29 08:23 UTC, boshmaf approved these changes

2022-05-29 08:24 UTC, merged